name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .nvmrc

        # Use pnpm based on packageManager in package.json via corepack.
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
