// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-wasm-crypto-test.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "WasmCryptoTestSpec.h"

@interface WasmCryptoTest : NSObject <NativeWasmCryptoTestSpec>
#else
#import <React/RCTBridgeModule.h>

@interface WasmCryptoTest : NSObject <RCTBridgeModule>
#endif

@end